# Generated by Django 4.2.4 on 2023-08-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("main_topic", models.TextField(max_length=1000)),
                ("topic1", models.TextField(blank=True, max_length=1000, null=True)),
                ("image1", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
        ),
    ]
